/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XDroneIdeModule /* implements AbstractXDroneIdeModule  */{
}
