/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.web;

import com.google.inject.Injector;
import ic.ac.uk.xdrone.XDroneStandaloneSetup;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class XDroneWebSetup extends XDroneStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from XDroneRuntimeModule to Module"
      + "\nType mismatch: cannot convert from XDroneIdeModule to Module"
      + "\nType mismatch: cannot convert from XDroneWebModule to Module");
  }
}
