version: '2'
services:
  master:
    image: "xdrone"
    container_name: master
    command: roscore
  ardrone:
    image: "xdrone"
    container_name: ardrone
    environment:
      - "ROS_HOSTNAME=ardrone"
      - "ROS_MASTER_URI=http://master:11311"
    command: /bin/bash /xdrone/run_ardrone.sh
  tomcat:
    image: "xdrone"
    container_name: tomcat
    environment:
      - "ROS_HOSTNAME=tomcat"
      - "ROS_MASTER_URI=http://master:11311"
    ports: 
    - "8888:8080"
    command: /bin/bash /opt/tomcat/8_0/bin/catalina.sh run 
