/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.xDrone;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fly</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ic.ac.uk.xdrone.xDrone.Fly#getTakeoff <em>Takeoff</em>}</li>
 *   <li>{@link ic.ac.uk.xdrone.xDrone.Fly#getCommands <em>Commands</em>}</li>
 *   <li>{@link ic.ac.uk.xdrone.xDrone.Fly#getLand <em>Land</em>}</li>
 * </ul>
 *
 * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getFly()
 * @model
 * @generated
 */
public interface Fly extends EObject
{
  /**
   * Returns the value of the '<em><b>Takeoff</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Takeoff</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Takeoff</em>' attribute list.
   * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getFly_Takeoff()
   * @model unique="false"
   * @generated
   */
  EList<String> getTakeoff();

  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference list.
   * The list contents are of type {@link ic.ac.uk.xdrone.xDrone.SuperCommand}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commands</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference list.
   * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getFly_Commands()
   * @model containment="true"
   * @generated
   */
  EList<SuperCommand> getCommands();

  /**
   * Returns the value of the '<em><b>Land</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Land</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Land</em>' attribute list.
   * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getFly_Land()
   * @model unique="false"
   * @generated
   */
  EList<String> getLand();

} // Fly
