/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.xDrone;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Origin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ic.ac.uk.xdrone.xDrone.Origin#getX <em>X</em>}</li>
 *   <li>{@link ic.ac.uk.xdrone.xDrone.Origin#getZ <em>Z</em>}</li>
 *   <li>{@link ic.ac.uk.xdrone.xDrone.Origin#getY <em>Y</em>}</li>
 * </ul>
 *
 * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getOrigin()
 * @model
 * @generated
 */
public interface Origin extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>X</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(String)
   * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getOrigin_X()
   * @model
   * @generated
   */
  String getX();

  /**
   * Sets the value of the '{@link ic.ac.uk.xdrone.xDrone.Origin#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(String value);

  /**
   * Returns the value of the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Z</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Z</em>' attribute.
   * @see #setZ(String)
   * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getOrigin_Z()
   * @model
   * @generated
   */
  String getZ();

  /**
   * Sets the value of the '{@link ic.ac.uk.xdrone.xDrone.Origin#getZ <em>Z</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Z</em>' attribute.
   * @see #getZ()
   * @generated
   */
  void setZ(String value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Y</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(String)
   * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getOrigin_Y()
   * @model
   * @generated
   */
  String getY();

  /**
   * Sets the value of the '{@link ic.ac.uk.xdrone.xDrone.Origin#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(String value);

} // Origin
