/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.xDrone;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Super Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getSuperCommand()
 * @model
 * @generated
 */
public interface SuperCommand extends EObject
{
} // SuperCommand
