/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.xDrone;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Walls</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ic.ac.uk.xdrone.xDrone.Walls#getFront <em>Front</em>}</li>
 *   <li>{@link ic.ac.uk.xdrone.xDrone.Walls#getRight <em>Right</em>}</li>
 *   <li>{@link ic.ac.uk.xdrone.xDrone.Walls#getBack <em>Back</em>}</li>
 *   <li>{@link ic.ac.uk.xdrone.xDrone.Walls#getLeft <em>Left</em>}</li>
 * </ul>
 *
 * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getWalls()
 * @model
 * @generated
 */
public interface Walls extends EObject
{
  /**
   * Returns the value of the '<em><b>Front</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Front</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Front</em>' attribute.
   * @see #setFront(String)
   * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getWalls_Front()
   * @model
   * @generated
   */
  String getFront();

  /**
   * Sets the value of the '{@link ic.ac.uk.xdrone.xDrone.Walls#getFront <em>Front</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Front</em>' attribute.
   * @see #getFront()
   * @generated
   */
  void setFront(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' attribute.
   * @see #setRight(String)
   * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getWalls_Right()
   * @model
   * @generated
   */
  String getRight();

  /**
   * Sets the value of the '{@link ic.ac.uk.xdrone.xDrone.Walls#getRight <em>Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' attribute.
   * @see #getRight()
   * @generated
   */
  void setRight(String value);

  /**
   * Returns the value of the '<em><b>Back</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Back</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Back</em>' attribute.
   * @see #setBack(String)
   * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getWalls_Back()
   * @model
   * @generated
   */
  String getBack();

  /**
   * Sets the value of the '{@link ic.ac.uk.xdrone.xDrone.Walls#getBack <em>Back</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Back</em>' attribute.
   * @see #getBack()
   * @generated
   */
  void setBack(String value);

  /**
   * Returns the value of the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' attribute.
   * @see #setLeft(String)
   * @see ic.ac.uk.xdrone.xDrone.XDronePackage#getWalls_Left()
   * @model
   * @generated
   */
  String getLeft();

  /**
   * Sets the value of the '{@link ic.ac.uk.xdrone.xDrone.Walls#getLeft <em>Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' attribute.
   * @see #getLeft()
   * @generated
   */
  void setLeft(String value);

} // Walls
