/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.xDrone;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ic.ac.uk.xdrone.xDrone.XDroneFactory
 * @model kind="package"
 * @generated
 */
public interface XDronePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xDrone";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.ic/uk/xdrone/XDrone";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xDrone";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XDronePackage eINSTANCE = ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl.init();

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.ProgramImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__MAIN = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.MainImpl <em>Main</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.MainImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getMain()
   * @generated
   */
  int MAIN = 1;

  /**
   * The feature id for the '<em><b>Takeoff</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__TAKEOFF = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__COMMANDS = 1;

  /**
   * The feature id for the '<em><b>Land</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__LAND = 2;

  /**
   * The number of structural features of the '<em>Main</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.UserFunctionImpl <em>User Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.UserFunctionImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getUserFunction()
   * @generated
   */
  int USER_FUNCTION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Func</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FUNCTION__FUNC = 1;

  /**
   * The number of structural features of the '<em>User Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FUNCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.SuperCommandImpl <em>Super Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.SuperCommandImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getSuperCommand()
   * @generated
   */
  int SUPER_COMMAND = 3;

  /**
   * The number of structural features of the '<em>Super Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPER_COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.CommandImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 4;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = SUPER_COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.UpImpl <em>Up</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.UpImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getUp()
   * @generated
   */
  int UP = 5;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Up</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.DownImpl <em>Down</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.DownImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getDown()
   * @generated
   */
  int DOWN = 6;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Down</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.LeftImpl <em>Left</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.LeftImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getLeft()
   * @generated
   */
  int LEFT = 7;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Left</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.RightImpl <em>Right</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.RightImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRight()
   * @generated
   */
  int RIGHT = 8;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Right</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.ForwardImpl <em>Forward</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.ForwardImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getForward()
   * @generated
   */
  int FORWARD = 9;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Forward</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.BackwardImpl <em>Backward</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.BackwardImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getBackward()
   * @generated
   */
  int BACKWARD = 10;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Backward</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.RotateLImpl <em>Rotate L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.RotateLImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRotateL()
   * @generated
   */
  int ROTATE_L = 11;

  /**
   * The feature id for the '<em><b>Angle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_L__ANGLE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rotate L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_L_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.RotateRImpl <em>Rotate R</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.RotateRImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRotateR()
   * @generated
   */
  int ROTATE_R = 12;

  /**
   * The feature id for the '<em><b>Angle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_R__ANGLE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rotate R</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_R_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.WaitImpl <em>Wait</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.WaitImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getWait()
   * @generated
   */
  int WAIT = 13;

  /**
   * The feature id for the '<em><b>Seconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT__SECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Wait</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.MoveImpl <em>Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.MoveImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getMove()
   * @generated
   */
  int MOVE = 14;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__Y = 1;

  /**
   * The feature id for the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__Z = 2;

  /**
   * The number of structural features of the '<em>Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.FunctionNameImpl <em>Function Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.FunctionNameImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getFunctionName()
   * @generated
   */
  int FUNCTION_NAME = 15;

  /**
   * The feature id for the '<em><b>Func name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_NAME__FUNC_NAME = SUPER_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Function Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_NAME_FEATURE_COUNT = SUPER_COMMAND_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link ic.ac.uk.xdrone.xDrone.Program#getMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Main</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Program#getMain()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Main();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Main <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Main
   * @generated
   */
  EClass getMain();

  /**
   * Returns the meta object for the attribute list '{@link ic.ac.uk.xdrone.xDrone.Main#getTakeoff <em>Takeoff</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Takeoff</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Main#getTakeoff()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_Takeoff();

  /**
   * Returns the meta object for the containment reference list '{@link ic.ac.uk.xdrone.xDrone.Main#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Main#getCommands()
   * @see #getMain()
   * @generated
   */
  EReference getMain_Commands();

  /**
   * Returns the meta object for the attribute list '{@link ic.ac.uk.xdrone.xDrone.Main#getLand <em>Land</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Land</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Main#getLand()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_Land();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.UserFunction <em>User Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Function</em>'.
   * @see ic.ac.uk.xdrone.xDrone.UserFunction
   * @generated
   */
  EClass getUserFunction();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.UserFunction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ic.ac.uk.xdrone.xDrone.UserFunction#getName()
   * @see #getUserFunction()
   * @generated
   */
  EAttribute getUserFunction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link ic.ac.uk.xdrone.xDrone.UserFunction#getFunc <em>Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Func</em>'.
   * @see ic.ac.uk.xdrone.xDrone.UserFunction#getFunc()
   * @see #getUserFunction()
   * @generated
   */
  EReference getUserFunction_Func();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.SuperCommand <em>Super Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Super Command</em>'.
   * @see ic.ac.uk.xdrone.xDrone.SuperCommand
   * @generated
   */
  EClass getSuperCommand();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Up <em>Up</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Up</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Up
   * @generated
   */
  EClass getUp();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Up#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Up#getDistance()
   * @see #getUp()
   * @generated
   */
  EAttribute getUp_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Down <em>Down</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Down</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Down
   * @generated
   */
  EClass getDown();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Down#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Down#getDistance()
   * @see #getDown()
   * @generated
   */
  EAttribute getDown_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Left <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Left</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Left
   * @generated
   */
  EClass getLeft();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Left#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Left#getDistance()
   * @see #getLeft()
   * @generated
   */
  EAttribute getLeft_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Right <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Right</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Right
   * @generated
   */
  EClass getRight();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Right#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Right#getDistance()
   * @see #getRight()
   * @generated
   */
  EAttribute getRight_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Forward <em>Forward</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Forward</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Forward
   * @generated
   */
  EClass getForward();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Forward#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Forward#getDistance()
   * @see #getForward()
   * @generated
   */
  EAttribute getForward_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Backward <em>Backward</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Backward</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Backward
   * @generated
   */
  EClass getBackward();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Backward#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Backward#getDistance()
   * @see #getBackward()
   * @generated
   */
  EAttribute getBackward_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.RotateL <em>Rotate L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate L</em>'.
   * @see ic.ac.uk.xdrone.xDrone.RotateL
   * @generated
   */
  EClass getRotateL();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.RotateL#getAngle <em>Angle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Angle</em>'.
   * @see ic.ac.uk.xdrone.xDrone.RotateL#getAngle()
   * @see #getRotateL()
   * @generated
   */
  EAttribute getRotateL_Angle();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.RotateR <em>Rotate R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate R</em>'.
   * @see ic.ac.uk.xdrone.xDrone.RotateR
   * @generated
   */
  EClass getRotateR();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.RotateR#getAngle <em>Angle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Angle</em>'.
   * @see ic.ac.uk.xdrone.xDrone.RotateR#getAngle()
   * @see #getRotateR()
   * @generated
   */
  EAttribute getRotateR_Angle();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Wait <em>Wait</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wait</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Wait
   * @generated
   */
  EClass getWait();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Wait#getSeconds <em>Seconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Seconds</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Wait#getSeconds()
   * @see #getWait()
   * @generated
   */
  EAttribute getWait_Seconds();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Move <em>Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Move
   * @generated
   */
  EClass getMove();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Move#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Move#getX()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_X();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Move#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Move#getY()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Y();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Move#getZ <em>Z</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Z</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Move#getZ()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Z();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.FunctionName <em>Function Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Name</em>'.
   * @see ic.ac.uk.xdrone.xDrone.FunctionName
   * @generated
   */
  EClass getFunctionName();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.FunctionName#getFunc_name <em>Func name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Func name</em>'.
   * @see ic.ac.uk.xdrone.xDrone.FunctionName#getFunc_name()
   * @see #getFunctionName()
   * @generated
   */
  EAttribute getFunctionName_Func_name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XDroneFactory getXDroneFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.ProgramImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__MAIN = eINSTANCE.getProgram_Main();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.MainImpl <em>Main</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.MainImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getMain()
     * @generated
     */
    EClass MAIN = eINSTANCE.getMain();

    /**
     * The meta object literal for the '<em><b>Takeoff</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__TAKEOFF = eINSTANCE.getMain_Takeoff();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN__COMMANDS = eINSTANCE.getMain_Commands();

    /**
     * The meta object literal for the '<em><b>Land</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__LAND = eINSTANCE.getMain_Land();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.UserFunctionImpl <em>User Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.UserFunctionImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getUserFunction()
     * @generated
     */
    EClass USER_FUNCTION = eINSTANCE.getUserFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_FUNCTION__NAME = eINSTANCE.getUserFunction_Name();

    /**
     * The meta object literal for the '<em><b>Func</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_FUNCTION__FUNC = eINSTANCE.getUserFunction_Func();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.SuperCommandImpl <em>Super Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.SuperCommandImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getSuperCommand()
     * @generated
     */
    EClass SUPER_COMMAND = eINSTANCE.getSuperCommand();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.CommandImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.UpImpl <em>Up</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.UpImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getUp()
     * @generated
     */
    EClass UP = eINSTANCE.getUp();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UP__DISTANCE = eINSTANCE.getUp_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.DownImpl <em>Down</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.DownImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getDown()
     * @generated
     */
    EClass DOWN = eINSTANCE.getDown();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOWN__DISTANCE = eINSTANCE.getDown_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.LeftImpl <em>Left</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.LeftImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getLeft()
     * @generated
     */
    EClass LEFT = eINSTANCE.getLeft();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEFT__DISTANCE = eINSTANCE.getLeft_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.RightImpl <em>Right</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.RightImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRight()
     * @generated
     */
    EClass RIGHT = eINSTANCE.getRight();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RIGHT__DISTANCE = eINSTANCE.getRight_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.ForwardImpl <em>Forward</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.ForwardImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getForward()
     * @generated
     */
    EClass FORWARD = eINSTANCE.getForward();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORWARD__DISTANCE = eINSTANCE.getForward_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.BackwardImpl <em>Backward</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.BackwardImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getBackward()
     * @generated
     */
    EClass BACKWARD = eINSTANCE.getBackward();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BACKWARD__DISTANCE = eINSTANCE.getBackward_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.RotateLImpl <em>Rotate L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.RotateLImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRotateL()
     * @generated
     */
    EClass ROTATE_L = eINSTANCE.getRotateL();

    /**
     * The meta object literal for the '<em><b>Angle</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_L__ANGLE = eINSTANCE.getRotateL_Angle();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.RotateRImpl <em>Rotate R</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.RotateRImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRotateR()
     * @generated
     */
    EClass ROTATE_R = eINSTANCE.getRotateR();

    /**
     * The meta object literal for the '<em><b>Angle</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_R__ANGLE = eINSTANCE.getRotateR_Angle();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.WaitImpl <em>Wait</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.WaitImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getWait()
     * @generated
     */
    EClass WAIT = eINSTANCE.getWait();

    /**
     * The meta object literal for the '<em><b>Seconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WAIT__SECONDS = eINSTANCE.getWait_Seconds();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.MoveImpl <em>Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.MoveImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getMove()
     * @generated
     */
    EClass MOVE = eINSTANCE.getMove();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__X = eINSTANCE.getMove_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__Y = eINSTANCE.getMove_Y();

    /**
     * The meta object literal for the '<em><b>Z</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__Z = eINSTANCE.getMove_Z();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.FunctionNameImpl <em>Function Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.FunctionNameImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getFunctionName()
     * @generated
     */
    EClass FUNCTION_NAME = eINSTANCE.getFunctionName();

    /**
     * The meta object literal for the '<em><b>Func name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION_NAME__FUNC_NAME = eINSTANCE.getFunctionName_Func_name();

  }

} //XDronePackage
