/**
 * generated by Xtext 2.17.0
 */
package ic.ac.uk.xdrone.xDrone;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ic.ac.uk.xdrone.xDrone.XDroneFactory
 * @model kind="package"
 * @generated
 */
public interface XDronePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xDrone";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.ic/uk/xdrone/XDrone";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xDrone";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XDronePackage eINSTANCE = ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl.init();

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.ProgramImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Fly</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__FLY = 0;

  /**
   * The feature id for the '<em><b>Environment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__ENVIRONMENT = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.FlyImpl <em>Fly</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.FlyImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getFly()
   * @generated
   */
  int FLY = 1;

  /**
   * The feature id for the '<em><b>Takeoff</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLY__TAKEOFF = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLY__COMMANDS = 1;

  /**
   * The feature id for the '<em><b>Land</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLY__LAND = 2;

  /**
   * The number of structural features of the '<em>Fly</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.EnvironmentImpl <em>Environment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.EnvironmentImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getEnvironment()
   * @generated
   */
  int ENVIRONMENT = 2;

  /**
   * The feature id for the '<em><b>Drone</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__DRONE = 0;

  /**
   * The feature id for the '<em><b>Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__OBJECTS = 1;

  /**
   * The number of structural features of the '<em>Environment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.UserFunctionImpl <em>User Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.UserFunctionImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getUserFunction()
   * @generated
   */
  int USER_FUNCTION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Func</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FUNCTION__FUNC = 1;

  /**
   * The number of structural features of the '<em>User Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FUNCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.SuperCommandImpl <em>Super Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.SuperCommandImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getSuperCommand()
   * @generated
   */
  int SUPER_COMMAND = 4;

  /**
   * The number of structural features of the '<em>Super Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPER_COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.CommandImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 5;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = SUPER_COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.UpImpl <em>Up</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.UpImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getUp()
   * @generated
   */
  int UP = 6;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Up</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.DownImpl <em>Down</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.DownImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getDown()
   * @generated
   */
  int DOWN = 7;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Down</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.LeftImpl <em>Left</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.LeftImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getLeft()
   * @generated
   */
  int LEFT = 8;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Left</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.RightImpl <em>Right</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.RightImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRight()
   * @generated
   */
  int RIGHT = 9;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Right</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.ForwardImpl <em>Forward</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.ForwardImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getForward()
   * @generated
   */
  int FORWARD = 10;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Forward</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.BackwardImpl <em>Backward</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.BackwardImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getBackward()
   * @generated
   */
  int BACKWARD = 11;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD__DISTANCE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Backward</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.RotateLImpl <em>Rotate L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.RotateLImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRotateL()
   * @generated
   */
  int ROTATE_L = 12;

  /**
   * The feature id for the '<em><b>Angle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_L__ANGLE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rotate L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_L_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.RotateRImpl <em>Rotate R</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.RotateRImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRotateR()
   * @generated
   */
  int ROTATE_R = 13;

  /**
   * The feature id for the '<em><b>Angle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_R__ANGLE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rotate R</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_R_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.WaitImpl <em>Wait</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.WaitImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getWait()
   * @generated
   */
  int WAIT = 14;

  /**
   * The feature id for the '<em><b>Seconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT__SECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Wait</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.MoveImpl <em>Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.MoveImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getMove()
   * @generated
   */
  int MOVE = 15;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__Y = 1;

  /**
   * The feature id for the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__Z = 2;

  /**
   * The number of structural features of the '<em>Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.FunctionNameImpl <em>Function Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.FunctionNameImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getFunctionName()
   * @generated
   */
  int FUNCTION_NAME = 16;

  /**
   * The feature id for the '<em><b>Func name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_NAME__FUNC_NAME = SUPER_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Function Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_NAME_FEATURE_COUNT = SUPER_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.DroneImpl <em>Drone</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.DroneImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getDrone()
   * @generated
   */
  int DRONE = 17;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE__X = 0;

  /**
   * The feature id for the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE__Z = 1;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE__Y = 2;

  /**
   * The number of structural features of the '<em>Drone</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ic.ac.uk.xdrone.xDrone.impl.ObjectImpl <em>Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ic.ac.uk.xdrone.xDrone.impl.ObjectImpl
   * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getObject()
   * @generated
   */
  int OBJECT = 18;

  /**
   * The feature id for the '<em><b>Object name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__OBJECT_NAME = 0;

  /**
   * The feature id for the '<em><b>Sx</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__SX = 1;

  /**
   * The feature id for the '<em><b>Sz</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__SZ = 2;

  /**
   * The feature id for the '<em><b>Sy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__SY = 3;

  /**
   * The feature id for the '<em><b>Lx</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__LX = 4;

  /**
   * The feature id for the '<em><b>Lz</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__LZ = 5;

  /**
   * The feature id for the '<em><b>Ly</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__LY = 6;

  /**
   * The number of structural features of the '<em>Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FEATURE_COUNT = 7;


  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link ic.ac.uk.xdrone.xDrone.Program#getFly <em>Fly</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fly</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Program#getFly()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Fly();

  /**
   * Returns the meta object for the containment reference '{@link ic.ac.uk.xdrone.xDrone.Program#getEnvironment <em>Environment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Environment</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Program#getEnvironment()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Environment();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Fly <em>Fly</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fly</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Fly
   * @generated
   */
  EClass getFly();

  /**
   * Returns the meta object for the attribute list '{@link ic.ac.uk.xdrone.xDrone.Fly#getTakeoff <em>Takeoff</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Takeoff</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Fly#getTakeoff()
   * @see #getFly()
   * @generated
   */
  EAttribute getFly_Takeoff();

  /**
   * Returns the meta object for the containment reference list '{@link ic.ac.uk.xdrone.xDrone.Fly#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Fly#getCommands()
   * @see #getFly()
   * @generated
   */
  EReference getFly_Commands();

  /**
   * Returns the meta object for the attribute list '{@link ic.ac.uk.xdrone.xDrone.Fly#getLand <em>Land</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Land</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Fly#getLand()
   * @see #getFly()
   * @generated
   */
  EAttribute getFly_Land();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Environment <em>Environment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Environment</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Environment
   * @generated
   */
  EClass getEnvironment();

  /**
   * Returns the meta object for the containment reference list '{@link ic.ac.uk.xdrone.xDrone.Environment#getDrone <em>Drone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Drone</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Environment#getDrone()
   * @see #getEnvironment()
   * @generated
   */
  EReference getEnvironment_Drone();

  /**
   * Returns the meta object for the containment reference list '{@link ic.ac.uk.xdrone.xDrone.Environment#getObjects <em>Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objects</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Environment#getObjects()
   * @see #getEnvironment()
   * @generated
   */
  EReference getEnvironment_Objects();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.UserFunction <em>User Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Function</em>'.
   * @see ic.ac.uk.xdrone.xDrone.UserFunction
   * @generated
   */
  EClass getUserFunction();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.UserFunction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ic.ac.uk.xdrone.xDrone.UserFunction#getName()
   * @see #getUserFunction()
   * @generated
   */
  EAttribute getUserFunction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link ic.ac.uk.xdrone.xDrone.UserFunction#getFunc <em>Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Func</em>'.
   * @see ic.ac.uk.xdrone.xDrone.UserFunction#getFunc()
   * @see #getUserFunction()
   * @generated
   */
  EReference getUserFunction_Func();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.SuperCommand <em>Super Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Super Command</em>'.
   * @see ic.ac.uk.xdrone.xDrone.SuperCommand
   * @generated
   */
  EClass getSuperCommand();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Up <em>Up</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Up</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Up
   * @generated
   */
  EClass getUp();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Up#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Up#getDistance()
   * @see #getUp()
   * @generated
   */
  EAttribute getUp_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Down <em>Down</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Down</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Down
   * @generated
   */
  EClass getDown();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Down#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Down#getDistance()
   * @see #getDown()
   * @generated
   */
  EAttribute getDown_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Left <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Left</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Left
   * @generated
   */
  EClass getLeft();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Left#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Left#getDistance()
   * @see #getLeft()
   * @generated
   */
  EAttribute getLeft_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Right <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Right</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Right
   * @generated
   */
  EClass getRight();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Right#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Right#getDistance()
   * @see #getRight()
   * @generated
   */
  EAttribute getRight_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Forward <em>Forward</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Forward</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Forward
   * @generated
   */
  EClass getForward();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Forward#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Forward#getDistance()
   * @see #getForward()
   * @generated
   */
  EAttribute getForward_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Backward <em>Backward</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Backward</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Backward
   * @generated
   */
  EClass getBackward();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Backward#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Backward#getDistance()
   * @see #getBackward()
   * @generated
   */
  EAttribute getBackward_Distance();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.RotateL <em>Rotate L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate L</em>'.
   * @see ic.ac.uk.xdrone.xDrone.RotateL
   * @generated
   */
  EClass getRotateL();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.RotateL#getAngle <em>Angle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Angle</em>'.
   * @see ic.ac.uk.xdrone.xDrone.RotateL#getAngle()
   * @see #getRotateL()
   * @generated
   */
  EAttribute getRotateL_Angle();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.RotateR <em>Rotate R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate R</em>'.
   * @see ic.ac.uk.xdrone.xDrone.RotateR
   * @generated
   */
  EClass getRotateR();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.RotateR#getAngle <em>Angle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Angle</em>'.
   * @see ic.ac.uk.xdrone.xDrone.RotateR#getAngle()
   * @see #getRotateR()
   * @generated
   */
  EAttribute getRotateR_Angle();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Wait <em>Wait</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wait</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Wait
   * @generated
   */
  EClass getWait();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Wait#getSeconds <em>Seconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Seconds</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Wait#getSeconds()
   * @see #getWait()
   * @generated
   */
  EAttribute getWait_Seconds();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Move <em>Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Move
   * @generated
   */
  EClass getMove();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Move#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Move#getX()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_X();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Move#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Move#getY()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Y();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Move#getZ <em>Z</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Z</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Move#getZ()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Z();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.FunctionName <em>Function Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Name</em>'.
   * @see ic.ac.uk.xdrone.xDrone.FunctionName
   * @generated
   */
  EClass getFunctionName();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.FunctionName#getFunc_name <em>Func name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Func name</em>'.
   * @see ic.ac.uk.xdrone.xDrone.FunctionName#getFunc_name()
   * @see #getFunctionName()
   * @generated
   */
  EAttribute getFunctionName_Func_name();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Drone <em>Drone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Drone</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Drone
   * @generated
   */
  EClass getDrone();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Drone#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Drone#getX()
   * @see #getDrone()
   * @generated
   */
  EAttribute getDrone_X();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Drone#getZ <em>Z</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Z</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Drone#getZ()
   * @see #getDrone()
   * @generated
   */
  EAttribute getDrone_Z();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Drone#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Drone#getY()
   * @see #getDrone()
   * @generated
   */
  EAttribute getDrone_Y();

  /**
   * Returns the meta object for class '{@link ic.ac.uk.xdrone.xDrone.Object <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Object
   * @generated
   */
  EClass getObject();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Object#getObject_name <em>Object name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Object name</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Object#getObject_name()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Object_name();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Object#getSx <em>Sx</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sx</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Object#getSx()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Sx();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Object#getSz <em>Sz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sz</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Object#getSz()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Sz();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Object#getSy <em>Sy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sy</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Object#getSy()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Sy();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Object#getLx <em>Lx</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lx</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Object#getLx()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Lx();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Object#getLz <em>Lz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lz</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Object#getLz()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Lz();

  /**
   * Returns the meta object for the attribute '{@link ic.ac.uk.xdrone.xDrone.Object#getLy <em>Ly</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ly</em>'.
   * @see ic.ac.uk.xdrone.xDrone.Object#getLy()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Ly();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XDroneFactory getXDroneFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.ProgramImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Fly</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__FLY = eINSTANCE.getProgram_Fly();

    /**
     * The meta object literal for the '<em><b>Environment</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__ENVIRONMENT = eINSTANCE.getProgram_Environment();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.FlyImpl <em>Fly</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.FlyImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getFly()
     * @generated
     */
    EClass FLY = eINSTANCE.getFly();

    /**
     * The meta object literal for the '<em><b>Takeoff</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLY__TAKEOFF = eINSTANCE.getFly_Takeoff();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLY__COMMANDS = eINSTANCE.getFly_Commands();

    /**
     * The meta object literal for the '<em><b>Land</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLY__LAND = eINSTANCE.getFly_Land();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.EnvironmentImpl <em>Environment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.EnvironmentImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getEnvironment()
     * @generated
     */
    EClass ENVIRONMENT = eINSTANCE.getEnvironment();

    /**
     * The meta object literal for the '<em><b>Drone</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENVIRONMENT__DRONE = eINSTANCE.getEnvironment_Drone();

    /**
     * The meta object literal for the '<em><b>Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENVIRONMENT__OBJECTS = eINSTANCE.getEnvironment_Objects();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.UserFunctionImpl <em>User Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.UserFunctionImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getUserFunction()
     * @generated
     */
    EClass USER_FUNCTION = eINSTANCE.getUserFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_FUNCTION__NAME = eINSTANCE.getUserFunction_Name();

    /**
     * The meta object literal for the '<em><b>Func</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_FUNCTION__FUNC = eINSTANCE.getUserFunction_Func();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.SuperCommandImpl <em>Super Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.SuperCommandImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getSuperCommand()
     * @generated
     */
    EClass SUPER_COMMAND = eINSTANCE.getSuperCommand();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.CommandImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.UpImpl <em>Up</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.UpImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getUp()
     * @generated
     */
    EClass UP = eINSTANCE.getUp();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UP__DISTANCE = eINSTANCE.getUp_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.DownImpl <em>Down</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.DownImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getDown()
     * @generated
     */
    EClass DOWN = eINSTANCE.getDown();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOWN__DISTANCE = eINSTANCE.getDown_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.LeftImpl <em>Left</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.LeftImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getLeft()
     * @generated
     */
    EClass LEFT = eINSTANCE.getLeft();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEFT__DISTANCE = eINSTANCE.getLeft_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.RightImpl <em>Right</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.RightImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRight()
     * @generated
     */
    EClass RIGHT = eINSTANCE.getRight();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RIGHT__DISTANCE = eINSTANCE.getRight_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.ForwardImpl <em>Forward</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.ForwardImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getForward()
     * @generated
     */
    EClass FORWARD = eINSTANCE.getForward();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORWARD__DISTANCE = eINSTANCE.getForward_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.BackwardImpl <em>Backward</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.BackwardImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getBackward()
     * @generated
     */
    EClass BACKWARD = eINSTANCE.getBackward();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BACKWARD__DISTANCE = eINSTANCE.getBackward_Distance();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.RotateLImpl <em>Rotate L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.RotateLImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRotateL()
     * @generated
     */
    EClass ROTATE_L = eINSTANCE.getRotateL();

    /**
     * The meta object literal for the '<em><b>Angle</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_L__ANGLE = eINSTANCE.getRotateL_Angle();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.RotateRImpl <em>Rotate R</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.RotateRImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getRotateR()
     * @generated
     */
    EClass ROTATE_R = eINSTANCE.getRotateR();

    /**
     * The meta object literal for the '<em><b>Angle</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_R__ANGLE = eINSTANCE.getRotateR_Angle();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.WaitImpl <em>Wait</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.WaitImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getWait()
     * @generated
     */
    EClass WAIT = eINSTANCE.getWait();

    /**
     * The meta object literal for the '<em><b>Seconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WAIT__SECONDS = eINSTANCE.getWait_Seconds();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.MoveImpl <em>Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.MoveImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getMove()
     * @generated
     */
    EClass MOVE = eINSTANCE.getMove();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__X = eINSTANCE.getMove_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__Y = eINSTANCE.getMove_Y();

    /**
     * The meta object literal for the '<em><b>Z</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__Z = eINSTANCE.getMove_Z();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.FunctionNameImpl <em>Function Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.FunctionNameImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getFunctionName()
     * @generated
     */
    EClass FUNCTION_NAME = eINSTANCE.getFunctionName();

    /**
     * The meta object literal for the '<em><b>Func name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION_NAME__FUNC_NAME = eINSTANCE.getFunctionName_Func_name();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.DroneImpl <em>Drone</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.DroneImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getDrone()
     * @generated
     */
    EClass DRONE = eINSTANCE.getDrone();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRONE__X = eINSTANCE.getDrone_X();

    /**
     * The meta object literal for the '<em><b>Z</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRONE__Z = eINSTANCE.getDrone_Z();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRONE__Y = eINSTANCE.getDrone_Y();

    /**
     * The meta object literal for the '{@link ic.ac.uk.xdrone.xDrone.impl.ObjectImpl <em>Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ic.ac.uk.xdrone.xDrone.impl.ObjectImpl
     * @see ic.ac.uk.xdrone.xDrone.impl.XDronePackageImpl#getObject()
     * @generated
     */
    EClass OBJECT = eINSTANCE.getObject();

    /**
     * The meta object literal for the '<em><b>Object name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__OBJECT_NAME = eINSTANCE.getObject_Object_name();

    /**
     * The meta object literal for the '<em><b>Sx</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__SX = eINSTANCE.getObject_Sx();

    /**
     * The meta object literal for the '<em><b>Sz</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__SZ = eINSTANCE.getObject_Sz();

    /**
     * The meta object literal for the '<em><b>Sy</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__SY = eINSTANCE.getObject_Sy();

    /**
     * The meta object literal for the '<em><b>Lx</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__LX = eINSTANCE.getObject_Lx();

    /**
     * The meta object literal for the '<em><b>Lz</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__LZ = eINSTANCE.getObject_Lz();

    /**
     * The meta object literal for the '<em><b>Ly</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__LY = eINSTANCE.getObject_Ly();

  }

} //XDronePackage
